### ISSUE TITLE
As an HTML Programmer, I want to see how other people code games, so that I can be inspired to create more games for the community

### ISSUE THREAD

**Issue by xlgmokha** [CodeChica/minigame#2]
Acceptance Criteria:

* [ ] source code is public for people to read.
* [ ] there is an example of a multiplayer game.
* [ ] there is an example of a single player game.
* [ ] the content for this available on the internet.
* [ ] the home page listed all of the available games.

**Comment by daitanfutekina** [comment]
![wireframe](https://user-images.githubusercontent.com/80719857/142735785-5f3896ae-aa0a-4a69-910f-9f86f9482641.png)

**Comment by daitanfutekina** [comment]
secondary wireframe
![wireframe2](https://user-images.githubusercontent.com/80719857/142735998-5e293144-3b54-4ad5-890e-38ce793b5688.png)
me
